"""
Django settings for cmms project.

Generated by 'django-admin startproject' using Django 5.2.3.
"""

import os
from pathlib import Path


# ============================================================
# BASE DIRECTORY
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# DEBUG
#
# Local:
#   DJANGO_DEBUG=True
#
# Server:
#   DJANGO_DEBUG=False
# ============================================================

DEBUG = os.getenv(
    "DJANGO_DEBUG",
    "True"
).lower() in (
    "true",
    "1",
    "yes",
)


# ============================================================
# SECRET KEY
#
# Set DJANGO_SECRET_KEY on the production server.
# Never hard-code your real production secret key.
# ============================================================

SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY"
)

if not SECRET_KEY:

    if DEBUG:

        # Local development fallback only
        SECRET_KEY = (
            "django-insecure-local-development-key-change-this"
        )

    else:

        raise RuntimeError(
            "DJANGO_SECRET_KEY environment variable is not set."
        )


# ============================================================
# ALLOWED HOSTS
# ============================================================

ALLOWED_HOSTS = [
    "solar.ieng.tech",
    ".ieng.tech",
    "127.0.0.1",
    "localhost",
]


# ============================================================
# PROXY / HTTPS
#
# Required when Django is behind Nginx / reverse proxy.
# ============================================================

SECURE_PROXY_SSL_HEADER = (
    "HTTP_X_FORWARDED_PROTO",
    "https",
)


# ============================================================
# HTTPS SECURITY
# ============================================================

if DEBUG:

    # Local development
    SECURE_SSL_REDIRECT = False
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False

else:

    # Production server
    SECURE_SSL_REDIRECT = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True


# ============================================================
# CSRF TRUSTED ORIGINS
# ============================================================

CSRF_TRUSTED_ORIGINS = [
    "https://solar.ieng.tech",
    "https://*.ieng.tech",
]


# ============================================================
# SESSION CONFIGURATION
#
# IMPORTANT FOR EMAIL OTP
#
# This stores Django session information inside a signed cookie.
# Therefore django_session database storage is NOT required for
# your email OTP verification.
# ============================================================

SESSION_ENGINE = (
    "django.contrib.sessions.backends.signed_cookies"
)

SESSION_COOKIE_NAME = "solar_sessionid"

SESSION_COOKIE_HTTPONLY = True

SESSION_COOKIE_SAMESITE = "Lax"


# ============================================================
# APPLICATIONS
# ============================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "cmmsApp",
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [

    "django.middleware.security.SecurityMiddleware",

    "whitenoise.middleware.WhiteNoiseMiddleware",

    # Required for request.session
    "django.contrib.sessions.middleware.SessionMiddleware",

    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ============================================================
# ROOT URL CONFIGURATION
# ============================================================

ROOT_URLCONF = "cmms.urls"


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [
    {
        "BACKEND":
            "django.template.backends.django.DjangoTemplates",

        "DIRS": [
            BASE_DIR / "cmmsApp" / "templates",
        ],

        "APP_DIRS":
            True,

        "OPTIONS": {

            "context_processors": [

                "django.template.context_processors.request",

                "django.contrib.auth.context_processors.auth",

                "django.contrib.messages.context_processors.messages",
            ],

        },

    },
]


# ============================================================
# WSGI
# ============================================================

WSGI_APPLICATION = "cmms.wsgi.application"


# ============================================================
# DATABASE
#
# Your OTP does NOT use this database because SESSION_ENGINE
# is configured to signed_cookies.
#
# SQLite can remain because Django admin/auth/contenttypes are
# currently installed in your project.
# ============================================================

DATABASES = {

    "default": {

        "ENGINE":
            "django.db.backends.sqlite3",

        "NAME":
            BASE_DIR / "db.sqlite3",

    }

}


# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [

    {
        "NAME":
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator",
    },

    {
        "NAME":
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator",
    },

    {
        "NAME":
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator",
    },

    {
        "NAME":
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator",
    },

]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# ============================================================
# STATIC FILES
# ============================================================

STATIC_URL = "/static/"

STATIC_ROOT = (
    BASE_DIR / "static_collected"
)


# Local static directory
STATIC_DIR = (
    BASE_DIR / "static"
)


# Prevent staticfiles.W004 if /static does not exist
if STATIC_DIR.exists():

    STATICFILES_DIRS = [
        STATIC_DIR,
    ]

else:

    STATICFILES_DIRS = []


# ============================================================
# STORAGE / WHITENOISE
# ============================================================

STORAGES = {

    "default": {

        "BACKEND":
            "django.core.files.storage.FileSystemStorage",

    },

    "staticfiles": {

        "BACKEND":
            "whitenoise.storage."
            "CompressedManifestStaticFilesStorage",

    },

}


# ============================================================
# MEDIA FILES
# ============================================================

MEDIA_URL = "/media/"

MEDIA_ROOT = (
    BASE_DIR / "media"
)


# ============================================================
# DEFAULT PRIMARY KEY
# ============================================================

DEFAULT_AUTO_FIELD = (
    "django.db.models.BigAutoField"
)


# ============================================================
# EMAIL / SMTP
# ============================================================

EMAIL_BACKEND = (
    "django.core.mail.backends.smtp.EmailBackend"
)


# SMTP server
EMAIL_HOST = os.getenv(
    "EMAIL_HOST",
    "mail.ieng.tech"
)


# Port 465 for SSL
EMAIL_PORT = int(
    os.getenv(
        "EMAIL_PORT",
        "465"
    )
)


# Port 465 uses SSL
EMAIL_USE_SSL = True

EMAIL_USE_TLS = False


# ============================================================
# SMTP USER
#
# Set this on local/server:
#
# EMAIL_HOST_USER=your-email@ieng.tech
# ============================================================

EMAIL_HOST_USER = os.getenv(
    "EMAIL_HOST_USER",
    "test@ieng.tech"
)


# ============================================================
# SMTP PASSWORD
#
# Do NOT hard-code this.
#
# Set:
# EMAIL_HOST_PASSWORD=your-password
# ============================================================

EMAIL_HOST_PASSWORD = os.getenv(
    "EMAIL_HOST_PASSWORD",
    "test@iEng"
)


# ============================================================
# DEFAULT FROM EMAIL
# ============================================================

DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL",
    EMAIL_HOST_USER
)


# ============================================================
# EMAIL TIMEOUT
# ============================================================

EMAIL_TIMEOUT = 15


# ============================================================
# CONTACT RECIPIENTS
# ============================================================

CONTACT_RECIPIENTS = [

    email.strip()

    for email in os.getenv(
        "CONTACT_RECIPIENTS",
        (
            "shila@iengaust.com.au,"
            "test@ieng.tech,"
            "aarti@iengaust.com.au"
        )
    ).split(",")

    if email.strip()
]


# ============================================================
# REQUEST DEMO RECIPIENTS
# ============================================================

DEMO_RECIPIENTS = (
    CONTACT_RECIPIENTS
)


# ============================================================
# CONTACT INBOX
# ============================================================

CONTACT_INBOX = (
    CONTACT_RECIPIENTS[0]
    if CONTACT_RECIPIENTS
    else ""
)


# ============================================================
# GOOGLE RECAPTCHA
#
# Set these using environment variables.
# ============================================================

RECAPTCHA_SITE_KEY = os.getenv(
    "RECAPTCHA_SITE_KEY",
    "6LdJgJgsAAAAACrJJ-nuo1Iw2sBxiKpTWADZ5stZ"
)


RECAPTCHA_SECRET_KEY = os.getenv(
    "RECAPTCHA_SECRET_KEY",
    "6LdJgJgsAAAAAMtKmtGv8pLZ3y7pvxV0UAe7Sx10"
)


# ============================================================
# OPTIONAL CONTACT EXCEL STORAGE
# ============================================================

# CONTACT_SUBMISSIONS_XLSX = (
#     BASE_DIR / "contact_submissions.xlsx"
# )